# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: login
  tag: v1.0.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  name: Node
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
services:
istio:
  enabled: false
  weight: 100
auth:
  github:
    callback: http://localhost:32785/GitHubAuth/callback
  frontend: 
    success: http://localhost:32785/callback/success
    failure: http://localhost:32785/callback/failure
  
  